import GreenDiv from '~/components/GreenDiv';
import Section from '~/components/Section';
import Article from '~/components/article';
import Card from '~/components/card';
import Text from '~/components/ui/Text';
import Brand from '~/components/ui/brand';
import Stat from './stat';
import Hero from './Hero';
export default function MonofilamentWithMoreDurableLowSheddingPage() {
  return (
    <section className='bg-white'>
      <Hero />
      <div className='bg-[url(https://s3-alpha-sig.figma.com/img/4610/2b56/bc80aae287c84cc8aa21b38d7e35ec2a?Expires=1692576000&Signature=p8IrRoRFlfGhRVhyvR30S6QISRcXdPLCayeRdMuciO2kH88ChnjiTDDSSmABVkim03tcwltl4tfOjL8j7ENFawcZZpJZvStJY7iXO4FdxKEqstABiE7GnHmrC6JvCZ6asUJZlfigknXJ8sYH4k3yHykyhOpCpYSOmUcuO4hOPUPsxV3VR1gpTPGGWyv3v14jtPBz~RVvarYupRllEn6uSqAJA27PIY5kHksxsYYkomkbcuXgnL13TDQk0-pgp74cQ6Ih8-qLvvPPewBOfPYgmhDyTMA25-IbnTQdD6OV574VHyWD0UG-dlibqFtkBWS4Amvac4nlR8fPdGNXqs1Y8Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4)] bg-no-repeat bg-cover'>
        <Section
          image={`https://s3-alpha-sig.figma.com/img/cddc/42f4/5aa4c7162252800bf08963836e4de80e?Expires=1692576000&Signature=ImWjRpTIBFfL62VX7K3WHXCzYkH8MVZ8ax7dAgEHBSQ8oyd7dU2yEVgOdrp5q2b7QBS2Gkho9AZC1epK5ZHi~gcGx3Zw-8Gv7nJHBKYIj2mfcWFX5oLdDRTCMjinpdVquQXc2oaID9I-SuftKvEgA65osAnIdOTw8cyinV1N~2Ygx1JEhiHzMmJPWyrZekTg3B4yBXRg0mWpOqgMg3BVHd3i1amqhwZa~M3Nhyvf2iBt3-db7B17HmW3lyO07WmaL4pctpxxjP3z6aGD4qx-ZZbTBP80Oo~-mG~1pb5r3ApWh7G-j4~Q7NAgJNgyYzPp0tIc01IebokIfeHz8rONnw__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4`}
          extra={
            <p className='text-white'>
              Textiles shed tiny microfibers during use and washing, and these
              particles can enter the environment and the food chain, causing
              pollution.
            </p>
          }
        />
        <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 justify-items-center gap-10 pb-40 container'>
          <Card white />
          <Card white />
          <Card white />
        </div>
      </div>
      <Article
        overlay
        text='We are committed to producing high-quality and durable monofilaments while also paying attention to the microfiber shedding generated by our own products.'
        image='https://s3-alpha-sig.figma.com/img/ef67/9275/dd5c38b1a151fa248290e7c2addf3e31?Expires=1692576000&Signature=anwPDVeemdBLtCflTOgjQMdVMmr~L1VYAuQvlA84XEUKP99pDmOVS9hjkPRn9~C00fbbZodj6qbPBLfws0E86Rk6XaLlX~GAqy8hD0ImNUgoVTHhBB9Lep3la4e17lZqp1zF~TYSbEi-aWRVRVZLfBls16Aq6JRqo2vIzU6yrlZyfkJPuo-vymA0nKHHGqyd0O8dU86P1JLxh6dCSDQldGjQTJnT4tn1PoO86MRS-joiY866w0F3VkgUKoa1Nlb5wGiYxsSnfomIT7qXYQU8YTsHi-qifPaQtVC1uaX6~9Xh25gPGFk6LJ0~ZzQUcFyDhX0tpA2TV253vD-0SOEJxw__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4'
      />
      <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 justify-items-center gap-10 pb-40 container'>
        <Card />
        <Card />
        <Card />
      </div>
      <Stat className={'mb-20 lg:mb-28'} />
      <Section
        className='lg:flex lg:[&_img]:w-[600px]  '
        image={`https://s3-alpha-sig.figma.com/img/00f7/c001/49744f7529b6c6ca37b3133281460352?Expires=1692576000&Signature=b0lz17JYnAT-3-VKv7Jm5nwWh41d-dSK~qIyHJ2Ogl-BLF1Ll0xkEofiwkVABGWIYs2k9sbP8JGafllOH5NX8iRnfPGQ4pLYP1JhWCPvoMnYwzumsTEnGqqUTmT21UtMaYWg4mMUzXb4iYFLoFtsyBJ-j1jXZGNRPBeSs3eRTHS8mnAbCZzDT0RvFdZcW6o5W50DpLbJa1yjYgWSXR9-8mh7BpmOauMUUnLrePCjMQ6YfzA41X6uhm9Lk-Ze6JpfPKX6sTdIqwNEtwjpg~MZ9gwTzKOYAw1otLnIVJfin3IaNXHxjqPSOkdiGzVOnonxRO7TKB-xYkt-cr3GxF1NBQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4`}
        extra={
          <>
            <Text bold>
              RTS Goal for <br />
              #Microfiber Shedding
            </Text>
            <br />
            Textiles woven from monofilaments generally have poor
            skin-friendliness and a heavy plastic feel. In order to expand the
            application scope of monofilaments and achieve reduced Microfiber
            Shedding, our current finest monofilament is 50D, and we continue to
            invest in development towards a direction that is thinner, softer,
            and more elastic.
          </>
        }
      />
    </section>
  );
}

const data = [
  {
    label: 'Specializing in monofilament to provide solutions.',
    text: 'Built on 45 years of monofilament development and manufacturing experience, we offer robust solutions to address the challenges.',
  },
  {
    label:
      'Striving for a sustainable model that combines both economic and environmental considerations.',
    text: 'Through innovative closed-loop methods, we pursue sustainable development and create shared economic value.',
  },
];
